version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:1.27.0
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  db:
    container_name: database
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - database:/var/lib/postgresql/data

  frontend:
    container_name: frontend
    build: ./example-frontend
    image: frontend
    ports:
      - 5000:5000

  backend:
    container_name: backend
    build: ./example-backend
    image: backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres

  redis:
    container_name: redis
    image: redis:latest

volumes:
  database:
